sudo: required

services:
  - docker

before_install:
  - docker  build --tag lbrady/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo 'success'

after_success:
  - docker  build --tag lbrady/multi-client ./client
  - docker  build --tag lbrady/multi-server ./server
  - docker  build --tag lbrady/multi-worker ./worker
  - docker  build --tag lbrady/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lbrady/multi-client
  - docker push lbrady/multi-server
  - docker push lbrady/multi-worker
  - docker push lbrady/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
